name: AndroidBuild

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4.1.0

      - name: Set up JDK 17
        uses: actions/setup-java@v3.13.0
        with:
          distribution: 'adopt'
          java-version: '17'

      - name: Grant execute permissions for gradlew
        run: chmod +x ./gradlew  # This grants execute permissions to gradlew script

      - name: Build Debug APK with Gradle
        run: ./gradlew assembleDebug  # This will build the debug APK

      - name: Get Current Date
        id: date
        run: echo "RELEASE_DATE=$(date +'%Y%m%d')" >> $GITHUB_ENV  # Just the date part for the release name

      - name: Create GitHub Release
        id: create_release
        uses: actions/create-release@v1
        with:
          tag_name: v${{ github.run_number }}-${{ env.RELEASE_DATE }}  # Use run number and release date
          release_name: "Release v${{ github.run_number }}-${{ env.RELEASE_DATE }}"  # Structured release name
          body: "Automated release with the latest APK"
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload APK to GitHub Release
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: app/build/outputs/apk/debug/app-debug.apk  # Path to the debug APK
          asset_name: MordhauMercs-debug.apk  # Change the name if needed
          asset_content_type: application/vnd.android.package-archive
